using FlashOWare.Tool.Core.CodeAnalysis;

namespace FlashOWare.Tool.Core.Tests.CodeAnalysis;

public class RoslynUtilitiesTests
{
    [Theory]
    [MemberData(nameof(GeneratedCodeAttribute))]
    public void IsGeneratedCode_GeneratedCodeAttribute_MarkedGenerated(string text, bool expected)
    {
        // Arrange
        var compilation = CreateCompilationChecked(text);
        // Act
        var isGenerated = RoslynUtilities.IsGeneratedCode(compilation);
        // Assert
        Assert.Equal(expected, isGenerated);
    }

    public static TheoryData<string, bool> GeneratedCodeAttribute()
    {
        return new()
        {
            { """[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("FlashOWare.Tool", "1.0.0.0")]""", true },
            { """
                using System.CodeDom.Compiler;
                using System.Reflection;
                [assembly: AssemblyCopyright("Copyright © FlashOWare 2023")]
                [assembly: GeneratedCodeAttribute("FlashOWare.Tool", "1.0.0.0")]
                [assembly: AssemblyTrademark("")]
                """, true },

            { "", false },
            { """
                [System.CodeDom.Compiler.GeneratedCodeAttribute("FlashOWare.Tool", "1.0.0.0")]
                public class RoslynUtilitiesTests { }
                """, false },
        };
    }

    [Theory]
    [MemberData(nameof(GeneratedFileName))]
    public void IsGeneratedCode_GeneratedFileName_MarkedGenerated(string name, bool expected)
    {
        // Arrange
        var document = CreateDocumentUnchecked(name, String.Empty);
        // Act
        var isGenerated = RoslynUtilities.IsGeneratedCode(document);
        // Assert
        Assert.Equal(expected, isGenerated);
    }

    public static TheoryData<string, bool> GeneratedFileName()
    {
        return new()
        {
            { "TemporaryGeneratedFile_File1.cs", true },
            { "File2.designer.cs", true },
            { "File3.generated.cs", true },
            { "File4.g.cs", true },
            { "File5.g.i.cs", true },

            { "", false },
            { "File.cs", false },
            { "TempGeneratedFile_File1.cs", false },
            { "TemporaryGenerated_File1.cs", false },
            { "File2.d.cs", false },
            { "File3.generate.cs", false },
            { "File4.gen.cs", false },
            { "File5.g.InitializeComponent.cs", false },
        };
    }

    [Theory]
    [MemberData(nameof(AutoGeneratedComment))]
    public void IsGeneratedCode_AutoGeneratedComment_MarkedGenerated(string text, bool expected)
    {
        // Arrange
        var syntaxRoot = CreateSyntaxRootChecked(text);
        // Act
        var isGenerated = RoslynUtilities.IsGeneratedCode(syntaxRoot);
        // Assert
        Assert.Equal(expected, isGenerated);
    }

    public static TheoryData<string, bool> AutoGeneratedComment()
    {
        return new()
        {
            { "//<auto-generated>", true },
            { "//<auto-generated/>", true },
            { "//<auto-generated />", true },
            { "// <auto-generated>", true },
            { "// <auto-generated/>", true },
            { "// <auto-generated />", true },

            { "/*<auto-generated>*/", true },
            { "/*<auto-generated/>*/", true },
            { "/*<auto-generated />*/", true },
            { "/* <auto-generated> */", true },
            { "/* <auto-generated/> */", true },
            { "/* <auto-generated /> */", true },

            { "//<autogenerated>", true },
            { "//<autogenerated/>", true },
            { "//<autogenerated />", true },
            { "// <autogenerated>", true },
            { "// <autogenerated/>", true },
            { "// <autogenerated />", true },

            { "/*<autogenerated>*/", true },
            { "/*<autogenerated/>*/", true },
            { "/*<autogenerated />*/", true },
            { "/* <autogenerated> */", true },
            { "/* <autogenerated/> */", true },
            { "/* <autogenerated /> */", true },

            { """
                //------------------------------------------------------------------------------
                // <auto-generated>
                //     This code was generated by a tool.
                //
                //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                // </auto-generated>
                //------------------------------------------------------------------------------
                """, true },
            { """
                /*
                <auto-generated>
                This code was generated by a tool.

                Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                </auto-generated>
                */
                """, true },

            { "", false },
            { """
                // Comment

                // <auto-generated/>
                """, true },
            { """
                /* Comment */
                /* <auto-generated/> */
                """, true },
            { """
                using System;
                // <auto-generated/>
                """, false },
            { """
                using System;
                /* <auto-generated/> */
                """, false },
        };
    }
}
