using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace FlashOWare.Tool.Core.CodeAnalysis;

public static partial class RoslynUtilities
{
    public static bool IsGeneratedCode(Compilation compilation)
    {
        return HasGeneratedCodeAttribute(compilation);
    }

    public static bool IsGeneratedCode(Document document)
    {
        return IsGeneratedFileName(document);
    }

    public static bool IsGeneratedCode(CompilationUnitSyntax syntaxRoot)
    {
        return HasAutoGeneratedComment(syntaxRoot);
    }
}

public static partial class RoslynUtilities
{
    private static bool HasGeneratedCodeAttribute(Compilation compilation)
    {
        INamedTypeSymbol? attribute = compilation.GetTypeByMetadataName("System.CodeDom.Compiler.GeneratedCodeAttribute");

        if (attribute is null)
        {
            return false;
        }

        return compilation.Assembly.GetAttributes()
            .Any(data => attribute.Equals(data.AttributeClass, SymbolEqualityComparer.Default));
    }

    private static bool IsGeneratedFileName(Document document)
    {
        if (document.Name.StartsWith("TemporaryGeneratedFile_", StringComparison.Ordinal) ||
            document.Name.EndsWith(".designer.cs", StringComparison.Ordinal) ||
            document.Name.EndsWith(".generated.cs", StringComparison.Ordinal) ||
            document.Name.EndsWith(".g.cs", StringComparison.Ordinal) ||
            document.Name.EndsWith(".g.i.cs", StringComparison.Ordinal))
        {
            return true;
        }

        return false;
    }

    private static bool HasAutoGeneratedComment(CompilationUnitSyntax syntaxRoot)
    {
        if (syntaxRoot.HasLeadingTrivia)
        {
            var triviaList = syntaxRoot.GetLeadingTrivia();

            foreach (var trivia in triviaList)
            {
                if (trivia.IsKind(SyntaxKind.SingleLineCommentTrivia))
                {
                    if (trivia.ToFullString().Contains("<auto-generated") ||
                        trivia.ToFullString().Contains("<autogenerated"))
                    {
                        return true;
                    }
                }
                else if (trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
                {
                    if (trivia.ToFullString().Contains("<auto-generated") ||
                        trivia.ToFullString().Contains("<autogenerated"))
                    {
                        return true;
                    }
                }
                else if (trivia.IsKind(SyntaxKind.EndOfLineTrivia))
                {
                    continue;
                }
                else
                {
                    return false;
                }
            }
        }

        return false;
    }
}
